FROM public.ecr.aws/lambda/python:3.12
WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

COPY src/summary_report/lambda.py ${LAMBDA_TASK_ROOT}/
COPY src/summary_report/visuals.py ${LAMBDA_TASK_ROOT}/
COPY src/summary_report/summary.py ${LAMBDA_TASK_ROOT}/
COPY src/summary_report/database.py ${LAMBDA_TASK_ROOT}/

CMD ["lambda.handler"]
